# netlify.toml

[build]
  command = "npm run build"    # Build command for Vite
  publish = "dist"             # Publish folder for the build output
  functions = ""  # Set this if you're using serverless functions (optional)

[build.environment]
  NODE_ENV = "production"      # Environment variable for production

[dev]
  command = "npm run dev"      # Command for local development (optional)
  port = 3000                 # Port for the local development server (optional)
